"""Fixed nine-scenario list and invariant values from frozen materials."""

from __future__ import annotations

FORMAT_NAME = "safepatch_session_replay"
FORMAT_VERSION = 2
HISTORICAL_FORMAT_VERSION = 1

SCENARIO_NAMES: tuple[str, ...] = (
    "success",
    "format_exhausted",
    "evidence_then_patch",
    "regen_exhausted",
    "rejected",
    "base_changed",
    "cancelled",
    "deadline_after_model",
    "unsupported_pytest",
)

# Counters asserted by capture. Values match frozen historical fingerprints
# and VerificationPolicy: SUCCEEDED -> all_tests_passed.
EXPECTED_INVARIANTS: dict[str, dict[str, object]] = {
    "success": {
        "status": "SUCCEEDED",
        "stop_reason": "all_tests_passed",
        "attempts_used": 1,
        "total_format_retries_used": 0,
        "total_patch_regeneration_retries": 0,
        "read_actions_used": 0,
        "exploration_read_actions_used": 0,
        "evidence_requests_used": 0,
        "patch_preflight_failures": 0,
        "patch_preflight_successes": 1,
        "pytest_scope_unsupported": False,
    },
    "format_exhausted": {
        "status": "MODEL_OUTPUT_INVALID",
        "stop_reason": "model_output_invalid",
        "attempts_used": 0,
        "total_format_retries_used": 2,
        "total_patch_regeneration_retries": 0,
        "read_actions_used": 0,
        "exploration_read_actions_used": 0,
        "evidence_requests_used": 0,
        "patch_preflight_failures": 0,
        "patch_preflight_successes": 0,
        "pytest_scope_unsupported": False,
    },
    "evidence_then_patch": {
        "status": "SUCCEEDED",
        "stop_reason": "all_tests_passed",
        "attempts_used": 1,
        "total_format_retries_used": 0,
        "total_patch_regeneration_retries": 0,
        "read_actions_used": 13,
        "exploration_read_actions_used": 12,
        "evidence_requests_used": 1,
        "patch_preflight_failures": 0,
        "patch_preflight_successes": 1,
        "pytest_scope_unsupported": False,
    },
    "regen_exhausted": {
        "status": "PATCH_NOT_APPLICABLE",
        "stop_reason": "patch_not_applicable",
        "attempts_used": 0,
        "total_format_retries_used": 0,
        "total_patch_regeneration_retries": 2,
        "read_actions_used": 2,
        "exploration_read_actions_used": 0,
        "evidence_requests_used": 0,
        "patch_preflight_failures": 3,
        "patch_preflight_successes": 0,
        "pytest_scope_unsupported": False,
    },
    "rejected": {
        "status": "REJECTED",
        "stop_reason": "user_rejected_patch",
        "attempts_used": 0,
        "total_format_retries_used": 0,
        "total_patch_regeneration_retries": 0,
        "read_actions_used": 0,
        "exploration_read_actions_used": 0,
        "evidence_requests_used": 0,
        "patch_preflight_failures": 0,
        "patch_preflight_successes": 1,
        "pytest_scope_unsupported": False,
    },
    "base_changed": {
        "status": "PATCH_BASE_CHANGED",
        "stop_reason": "patch_base_changed",
        "attempts_used": 0,
        "total_format_retries_used": 0,
        "total_patch_regeneration_retries": 0,
        "read_actions_used": 0,
        "exploration_read_actions_used": 0,
        "evidence_requests_used": 0,
        "patch_preflight_failures": 0,
        "patch_preflight_successes": 1,
        "pytest_scope_unsupported": False,
    },
    "cancelled": {
        "status": "ERROR",
        "stop_reason": "cancelled",
        "attempts_used": 0,
    },
    "deadline_after_model": {
        "status": "ERROR",
        "stop_reason": "session_deadline",
        "attempts_used": 0,
        "total_format_retries_used": 0,
        "total_patch_regeneration_retries": 0,
        "read_actions_used": 0,
        "exploration_read_actions_used": 0,
        "evidence_requests_used": 0,
        "patch_preflight_failures": 0,
        "patch_preflight_successes": 0,
        "pytest_scope_unsupported": False,
    },
    "unsupported_pytest": {
        "status": "PATCH_NOT_APPLICABLE",
        "stop_reason": "unsupported_pytest_collection",
        "attempts_used": 0,
        "total_format_retries_used": 0,
        "total_patch_regeneration_retries": 0,
        "read_actions_used": 0,
        "exploration_read_actions_used": 0,
        "evidence_requests_used": 0,
        "patch_preflight_failures": 0,
        "patch_preflight_successes": 0,
        "pytest_scope_unsupported": True,
    },
}

HISTORICAL_FINGERPRINT_KEYS: tuple[str, ...] = (
    "status",
    "stop_reason",
    "attempts_used",
    "total_format_retries_used",
    "consecutive_format_retries",
    "total_patch_regeneration_retries",
    "read_actions_used",
    "exploration_read_actions_used",
    "evidence_requests_used",
    "evidence_parameter_corrections_used",
    "hard_policy_violations",
    "total_no_progress_actions",
    "patch_preflight_failures",
    "patch_preflight_successes",
    "pytest_scope_unsupported",
    "summary_status",
    "summary_stop_reason",
    "summary_attempts_used",
    "model_calls",
    "logical_calls",
    "transport_attempts",
    "format_retries",
    "patch_regeneration",
    "read_budget",
    "event_order",
    "final_diff",
    "workspace_mod",
)

# cancelled historical fingerprint omitted several counters.
HISTORICAL_FINGERPRINT_KEYS_BY_SCENARIO: dict[str, tuple[str, ...]] = {
    "cancelled": (
        "status",
        "stop_reason",
        "attempts_used",
        "event_order",
        "final_diff",
        "last_error",
    ),
}

SUMMARY_COMPARE_KEYS: tuple[str, ...] = (
    "summary_schema_version",
    "status",
    "attempts_used",
    "changed_files",
    "baseline_tests_passed",
    "final_tests_passed",
    "request_verified",
    "verification_basis",
    "stop_reason",
    "consecutive_format_retries",
    "total_format_retries_used",
    "consecutive_patch_regeneration_retries",
    "total_patch_regeneration_retries",
    "patch_preflight_failures",
    "patch_preflight_successes",
    "patch_preflight_success_rate",
    "patch_apply_failures_after_preflight",
    "patch_apply_failures_without_preflight",
    "first_patch_applicable",
    "analysis",
    "read_budget",
)

OBSERVABILITY_COMPARE_KEYS: tuple[str, ...] = (
    "model",
    "tools",
    "retries",
    "tests",
)
